### ISSUE TITLE
keras2caffe

### ISSUE THREAD

**Issue by yonger001** [nerddd/SSRNet-caffe#1]
hello，would U like to share the keras2caffe scope U have modified？initial scope lacked a lot of layer，ex：multiply，tanh，merge。。。。waiting your reply and discussion，3Q！

**Comment by nerddd** [comment]
Updated

**Comment by yonger001** [comment]
hi,thank U for your reply,when I test the convert_ssrnet script,there is error as follow:
ValueError: Layer #53 (named "dense_1"), weight <tf.Variable 'dense_1/kernel:0' shape=(250, 3) dtype=float32_ref> has shape (250, 3), but the saved weight has shape (160, 3).
obviously,the shape is different between the saved weights and net, I used the official .h5,Have U test it?

**Comment by yonger001** [comment]
@nerddd hi,thank U for your reply,when I test the convert_ssrnet script,there is error as follow:
ValueError: Layer #53 (named "dense_1"), weight <tf.Variable 'dense_1/kernel:0' shape=(250, 3) dtype=float32_ref> has shape (250, 3), but the saved weight has shape (160, 3).
obviously,the shape is different between the saved weights and net, I used the official .h5,Have U test it?

**Comment by nerddd** [comment]
yeah， because the padding is differenf between tf and caffe , so you need to use the **SSR-Net** in my repo to change the padding way , retrain the model , use the retrained .h5 to transform . More specific, the SSRNet_model.py is modified , you can check.

**Comment by yonger001** [comment]
@nerddd thank U so much!!! would U like to share the .h5 which U have  retrained??

**Comment by liangheng** [comment]
@nerddd hello 
Could you please provide the.h5 file corresponding to caffemodel in your examples folder? 
Because I used my training. h5 conversion to caffemodel has problems with calling results. I want to know whether it's the conversion script or the training setup, so I want to compare your.h5

thanks

**Comment by nerddd** [comment]
@liangheng Sorry, the directory has been cleaned. You can use the script provied to retrain your model and then convert it. Or use #2 to change the source code of caffe.

**Comment by liangheng** [comment]
@nerddd Thank you very much .yeah, I have retrained the model using the script you provided and convert it. No errors were reported during the conversion, but when I called caffemodel after the conversion, I couldn't get the right results.And I can make sure I got it the right way, so what could be wrong with the conversion or other

**Comment by liangheng** [comment]
@nerddd hello 
sorry to bother you again
I found that the best models in keras were very poor after converting to caffemodel using the transformation script you provided. Have you tested the converted caffemodel？
I did the following experiment: I used keras to test that an image could be accurately dated. For the same image, I used the converted caffemodel to load it with python's caffe interface（eg: net = caffe.Net('ssrnet_3_3_3_64_1.0_1.0.prototxt', 'ssrnet_3_3_3_64_1.0_1.0.caffemodel', caffe.TEST)）, but could not get the same age, so I suspected that the conversion caused the problem or did I go wrong?
I can't send you an email to tell you my WeChat, could you please send me an email to tell me your contact information
thanks

**Comment by liangheng** [comment]
@nerddd hello 
sorry to bother you again
I found that the best models in keras were very poor after converting to caffemodel using the transformation script you provided. Have you tested the converted caffemodel？
I did the following experiment: I used keras to test that an image could be accurately dated. For the same image, I used the converted caffemodel to load it with python's caffe interface（eg: net = caffe.Net('ssrnet_3_3_3_64_1.0_1.0.prototxt', 'ssrnet_3_3_3_64_1.0_1.0.caffemodel', caffe.TEST)）, but could not get the same age, so I suspected that the conversion caused the problem or did I go wrong?
I can't send you an email to tell you my WeChat, could you please send me an email to tell me your contact information
thanks

**Comment by liangheng** [comment]
@nerddd I solverd this problem~
