### ISSUE TITLE
caffe model

### ISSUE THREAD

**Issue by blue-butterfly** [nerddd/SSRNet-caffe#3]
你好，转化一直不成功，能不能共享一下转化完成的caffemodel和deploy.prototxt 非常感谢！

**Comment by ReedZyd** [comment]
同上。

**Comment by nerddd** [comment]
@blue-butterfly @ReedZyd 已更新了，随机找了一个模型，以前训练好的不知道放哪去了，所以准确率可能不是很好，仅供参考

**Comment by ReedZyd** [comment]
请问准确率大概是多少呢

**Comment by nerddd** [comment]
找不到训练日志了，其实那个里面有提供训练脚本，可以自己训练一下，更直观一些
